/**
 * Emit a Tailwind v4 `globals.css` from a normalized TokenSet, mapping onto the
 * shadcn variable contract. Colors are converted to OKLCH; non-color tokens are
 * passed through. Also reports which contract tokens are missing — the silent
 * gaps that make a generated UI "look generically off."
 */
import { SHADCN_COLOR_TOKENS } from "./contract.js";
import { toOklchString } from "./color.js";
import type { TokenSet } from "./tokens.js";

export interface EmitResult {
  css: string;
  missing: string[]; // contract tokens with no value supplied
  extras: string[]; // custom tokens beyond the contract
  converted: number; // color values converted to oklch
}

const DEFAULT_RADIUS = "0.625rem";

export function emitGlobalsCss(set: TokenSet): EmitResult {
  const provided = new Set([
    ...Object.keys(set.light),
    ...Object.keys(set.dark),
  ]);
  const contract = new Set<string>(SHADCN_COLOR_TOKENS);
  const missing = SHADCN_COLOR_TOKENS.filter((t) => !provided.has(t));
  const extras = [...provided].filter((t) => !contract.has(t)).sort();

  let converted = 0;
  const convert = (value: string): string => {
    const oklch = toOklchString(value);
    if (oklch) {
      converted++;
      return oklch;
    }
    return value; // already a var/keyword/non-color — leave it
  };

  // Ordered token list: contract first (canonical order), then extras.
  const order = [...SHADCN_COLOR_TOKENS, ...extras];

  const rootLines: string[] = [];
  const darkLines: string[] = [];

  const radius = set.radius ?? DEFAULT_RADIUS;
  rootLines.push(`  --radius: ${radius};`);

  for (const token of order) {
    const lv = set.light[token];
    const dv = set.dark[token];
    if (lv != null) rootLines.push(`  --${token}: ${convert(lv)};`);
    if (dv != null) darkLines.push(`  --${token}: ${convert(dv)};`);
  }

  // Pass-through non-color tokens (spacing, shadows, custom radii…).
  for (const [name, value] of Object.entries(set.passthroughLight)) {
    rootLines.push(`  --${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(set.passthroughDark)) {
    darkLines.push(`  --${name}: ${value};`);
  }

  const themeLines = buildThemeInline(order, set);

  const css = `@import "tailwindcss";
@plugin "tailwindcss-animate";

@custom-variant dark (&:is(.dark *));

/* Generated by token-bridge — https://github.com/blw10210/token-bridge
   Edit your tokens source and regenerate rather than hand-editing this file. */

:root {
${rootLines.join("\n")}
}

.dark {
${darkLines.join("\n")}
}

@theme inline {
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
${themeLines.join("\n")}
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`;

  return { css, missing, extras, converted };
}

function buildThemeInline(order: string[], set: TokenSet): string[] {
  const lines: string[] = [];
  const seen = new Set<string>();
  for (const token of order) {
    if (set.light[token] == null && set.dark[token] == null) continue;
    if (seen.has(token)) continue;
    seen.add(token);
    lines.push(`  --color-${token}: var(--${token});`);
  }
  if (set.fonts) {
    for (const [name, stack] of Object.entries(set.fonts)) {
      lines.push(`  --font-${name}: ${stack};`);
    }
  }
  return lines;
}
